### ISSUE TITLE
Players are unable to join the server.

### ISSUE THREAD

**Issue by ImTravis** [MannyFlapjack/CheatBreakerAPI#1]
Error I am receiving: 

`29.06 18:08:23 [Server] INFO -1332 <--
29.06 18:08:23 [Server] ERROR [CheatBreakerAPI] Unhandled exception occured in onPacketSending(PacketEvent) for CheatBreakerAPI
29.06 18:08:23 [Server] INFO java.lang.IllegalStateException: Override onPacketSending to get notifcations of sent packets!
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.events.PacketAdapter.onPacketSending(PacketAdapter.java:317) ~[ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:633) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:609) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:286) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:254) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:385) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:61) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:349) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:317) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:110) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:76) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at net.minecraft.server.v1_7_R4.NetworkManager.b(NetworkManager.java:151) [aSpigot.jar:git-PaperSpigot-ba75d9a]
29.06 18:08:23 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
29.06 18:08:23 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
29.06 18:08:23 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
29.06 18:08:23 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$600(ChannelInjector.java:61) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$6.run(ChannelInjector.java:498) [ProtocolLib%20(1).jar:?]
29.06 18:08:23 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) [aSpigot.jar:git-PaperSpigot-ba75d9a]
29.06 18:08:23 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [aSpigot.jar:git-PaperSpigot-ba75d9a]
29.06 18:08:23 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:702) [aSpigot.jar:git-PaperSpigot-ba75d9a]
29.06 18:08:23 [Server] INFO at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [aSpigot.jar:git-PaperSpigot-ba75d9a]
29.06 18:08:23 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:644) [aSpigot.jar:git-PaperSpigot-ba75d9a]
29.06 18:08:23 [Server] INFO at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:550) [aSpigot.jar:git-PaperSpigot-ba75d9a]
29.06 18:08:23 [Server] INFO at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [aSpigot.jar:git-PaperSpigot-ba75d9a]
29.06 18:08:23 [Server] WARN [ProtocolLib] Warning: Cannot convert to a String with Apache: null
29.06 18:08:23 [Server] ERROR Parameters: 
29.06 18:08:23 [Server] INFO { a = (("TextComponent{text='You must be on CheatBreaker to join our server.', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}")), timestamp = 1530310103424 }
29.06 18:08:23 [Server] WARN An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
29.06 18:08:23 [Server] INFO java.nio.channels.ClosedChannelException`

**Comment by MannyFlapjack** [comment]
Interesting. Thank you for reporting. I'll be looking at this issue right now.

**Comment by MannyFlapjack** [comment]
Added other options for 1.7 excluding ProtocolLib
