### ISSUE TITLE
Spigot Version?

### ISSUE THREAD

**Issue by CustomETB** [MannyFlapjack/CheatBreakerAPI#2]
i tried with Spigot 1.7.10,1.7.9,1.7.2.

**Comment by MannyFlapjack** [comment]
The ProtocolLib version does not support 1.7.10. However, if you enable channels and disable ProtocolLib it should work fine.

It is best used on Bungee which works on any bungee version (that I know of)

**Comment by CustomETB** [comment]
hey, any bungeecord version? with 1.7.x bungee outdated, with 1.8.x outdated, with 1.5.2 outdated. any solution?
